[book]
authors = ["Saitama "]
language = "en"
multilingual = false
src = "src"
title = "The SaitaChain Parachain Host Implementers' Guide"

[preprocessor.graphviz]
command = "mdbook-graphviz"
[preprocessor.mermaid]
command = "mdbook-mermaid"
[preprocessor.last-changed]
command = "mdbook-last-changed"
renderer = ["html"]

[output.html]
additional-css = ["last-changed.css"]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
# Repository URL used in the last-changed link.
git-repository-url = "https://github.com/saitamahub/SaitaChain-Layer1/"

[output.linkcheck]
