#!/bin/sh

set -e

action="$1"
config_file="/etc/default/saitachain"

if [ "$action" = "configure" ]; then
  # Make user and group
  getent group saitachain >/dev/null 2>&1 || addgroup --system saitachain
  getent passwd saitachain >/dev/null 2>&1 ||
    adduser --system --home /home/saitachain --disabled-password \
    --ingroup saitachain saitachain
  if [ ! -e "$config_file" ]; then
    echo 'saitama_cli_ARGS=""' > /etc/default/saitachain
  fi
fi
